import test from 'node:test';
import assert from 'node:assert/strict';
import {nextStep,roll} from '../src/engine.js';
import * as old from '../src/journey-v1.js';
import {createJourney,nextJourneyStep,applyJourneyRoll,rollJourney,eventPool,trainingPool,combatOdds,saveDocument,loadDocument} from '../src/journey.js';
import {CANON,canonPool,lifeContext,dreamReadiness,shapeEvents,encounterTones,travelPool} from '../src/story.js';
import {QGIS_WORLD_SCHEMA,ensureSimulation,effectiveDanger,crewTurnWeights,resolveCrewTurns} from '../src/simulation.js';
import {WORLD_COUNTS,worldLocation,authoredRoutesFrom} from '../src/world-data.js';
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
function origin(overrides={}){const h=[],r=rng(451);const chosen={era:'New World opening',race:'Human',age:'24',faction:'Pirate',haki:'No',devilFruit:'No',fightingStyle:'Three-sword style',crewMode:'Go solo',...overrides};while(nextStep(h)){const s=nextStep(h),item=roll(h,r);if(chosen[s.id]!==undefined){assert(s.options.some(o=>o.value===chosen[s.id]),s.id);item.value=chosen[s.id];}h.push(item);}return h;}
const base=origin();
function choose(j,key,value){assert.equal(nextJourneyStep(j)?.key,key);return applyJourneyRoll(j,value);}
function battle(j,result='victory',id='buggy'){choose(j,'event','pirates');choose(j,'opponent',id);choose(j,'tone','hostile');choose(j,'instinct','Steady resolve');choose(j,'resolution',result);}
const weight=(options,value)=>options.find(o=>o.value===value)?.weight||0;
test('pirate and Marine wheels contain named canon characters and proper affiliations',()=>{const j=createJourney(base);choose(j,'event','marines');const options=nextJourneyStep(j).options;assert(options.some(o=>o.value==='smoker'&&o.label.includes('Marine')));assert(options.every(o=>CANON.some(c=>c.id===o.value&&c.kind==='marine')));assert(!options.some(o=>o.value==='seasoned'));});
test('era, region, crew membership and deaths filter cast eligibility',()=>{const j=createJourney(origin({era:'Roger’s final voyage'}));assert(canonPool(j,'pirates').some(o=>o.value==='roger'));assert(!canonPool(j,'pirates').some(o=>o.value==='luffy'));j.story.dead.push('roger');assert(!canonPool(j,'pirates').some(o=>o.value==='roger'));const modern=createJourney(base);modern.group='Straw Hat Pirates';assert(!canonPool(modern,'pirates').some(o=>o.value==='luffy'));});
test('encounters can be friendly; shared Marine allegiance strongly favors it',()=>{const pirate=createJourney(base),marine=createJourney(origin({faction:'Marine'})),smoker=CANON.find(c=>c.id==='smoker');assert(weight(encounterTones(marine,smoker),'friendly')>weight(encounterTones(pirate,smoker),'friendly'));choose(pirate,'event','pirates');choose(pirate,'opponent','luffy');choose(pirate,'tone','friendly');choose(pirate,'socialResult','alliance');assert.equal(pirate.chapter,1);assert.equal(pirate.wins,0);assert.equal(pirate.story.relationships.luffy.score,2);assert.match(pirate.log[0].effects.join(' '),/Monkey D. Luffy/);});
test('one hostile resolution; lethal victories remove the named character from all pools',()=>{const j=createJourney(base);battle(j,'lethal');assert.equal(j.pending,null);assert.equal(j.elapsedMonths,4);assert.equal(j.kills,1);assert(j.story.dead.includes('buggy'));assert(!canonPool(j,'pirates').some(o=>o.value==='buggy'));assert.equal(j.log[0].rolls.filter(r=>r.id.endsWith(':resolution')).length,1);assert.equal(j.log[0].encounter,'Buggy');});
test('huge opponent gaps are not erased by an aggressive impulse; fleeing still adds 7pp',()=>{const j=createJourney(base);const before=combatOdds(j,'shanks','Steady resolve'),after=combatOdds(j,'shanks','Aggressive impulse');assert(after.modifier.after-after.modifier.before<7);const flee=combatOdds(j,'shanks','Urge to flee');assert(Math.abs(flee.modifier.after-flee.modifier.before-7)<1e-9);assert(before.enemy>100);});
test('faction danger responds to world stability instead of using one global risk number',()=>{const pirate=createJourney(base),marine=createJourney(origin({faction:'Marine'}));ensureSimulation(pirate).stability=90;ensureSimulation(marine).stability=90;assert(effectiveDanger(marine)<=1);assert(effectiveDanger(pirate)>=4.5);ensureSimulation(pirate).stability=45;ensureSimulation(marine).stability=45;assert(effectiveDanger(marine)>=2.5&&effectiveDanger(marine)<=3.5);assert(effectiveDanger(pirate)>=3&&effectiveDanger(pirate)<=4.5);});
test('major world events can create local disasters and permanently erase travel destinations',()=>{const j=createJourney(base),start=j.story.location;choose(j,'event','world');assert(nextJourneyStep(j).options.some(o=>o.value==='Buster Call authorized'));choose(j,'worldResult','Buster Call authorized');assert(j.simulation.stability<88);assert((j.simulation.dangerZones[start]||0)>0);choose(j,'event','world');choose(j,'worldResult','An island is eradicated');assert.equal(j.simulation.destroyedLocations.length,1);assert(!travelPool(j).some(o=>j.simulation.destroyedLocations.includes(o.value)));});
test('crew members receive deterministic background turns with growth loyalty departure injury and death outcomes',()=>{const j=createJourney(base);j.crew=[{name:'Mira Test',role:'Navigator',race:'Human',canon:false}];ensureSimulation(j);const values=crewTurnWeights(j,j.crew[0],4).map(o=>o.value);for(const expected of ['advance','bond','leave','injured','death'])assert(values.includes(expected));const a=structuredClone(j),b=structuredClone(j);a.chapter=b.chapter=7;const ea=resolveCrewTurns(a,4,'travel'),eb=resolveCrewTurns(b,4,'travel');assert.deepEqual(ea,eb);assert.deepEqual(a.crew,b.crew);});
test('QGIS world contract preserves route danger faction and danger-zone fields from the authored map',()=>{for(const key of ['travel_days','danger_level','faction_access','outcome_chance'])assert(QGIS_WORLD_SCHEMA.routes.includes(key));for(const key of ['severity','faction','region_id'])assert(QGIS_WORLD_SCHEMA.dangerZones.includes(key));for(const key of ['danger_score','travel_days','faction'])assert(QGIS_WORLD_SCHEMA.worldRoutes.includes(key));});
test('QGIS world graph loads the complete cleaned map and authored Paradise routes',()=>{assert.equal(WORLD_COUNTS.locations,230);assert.equal(WORLD_COUNTS.authoredRoutes,45);assert.equal(WORLD_COUNTS.regions,8);assert.equal(WORLD_COUNTS.dangerZones,14);const foosha=worldLocation('Foosha Village');assert.equal(foosha.id,'island_foosha_village');assert.equal(foosha.region,'east_blue');const twins=worldLocation('Twins Cape');const routes=authoredRoutesFrom(twins);assert(routes.some(r=>r.toId==='island_whisky_peak'));assert(routes.some(r=>r.toId==='island_kyuka_island'));});
test('young new-fruit users favor focused practice while elders avoid physical grinding',()=>{const young=createJourney(origin({age:'16',devilFruit:'Yes',fruitMastery:'Just eaten'}));const adult=createJourney(origin({age:'32',devilFruit:'No'}));assert(lifeContext(young).freshFruit);assert(weight(eventPool(young),'training')>weight(eventPool(adult),'training')*4);assert(weight(trainingPool(young),'fruitMastery')>weight(trainingPool(young),'stamina')*5);const elder=createJourney(base);elder.ageMonths=80*12;assert(lifeContext(elder).elder);assert(!trainingPool(elder).some(o=>o.value==='stamina'));assert(weight(eventPool(elder),'teaching')>0);assert(weight(eventPool(elder),'training')<weight(eventPool(adult),'training'));});
test('giant life stages scale with race rather than treating age 80 as elderly',()=>{const j=createJourney(origin({race:'Giant',age:'90'}));j.ageMonths=80*12;assert.equal(lifeContext(j).elder,false);j.ageMonths=240*12;assert.equal(lifeContext(j).elder,true);});
test('newly eaten fruits create a learning arc; injuries and repetition alter probabilities',()=>{const j=createJourney(base);choose(j,'event','fruit');choose(j,'fruitType','Logia');choose(j,'fruitName',nextJourneyStep(j).options[0].value);choose(j,'fruitOutcome','eat');assert(lifeContext(j).freshFruit);const before=weight(eventPool(j),'recovery');j.injury=3;assert(weight(eventPool(j),'recovery')>before);const training=weight(eventPool(j),'training');j.log.push({event:'training',effects:[]},{event:'training',effects:[]});assert(weight(eventPool(j),'training')<training*.2);});
test('named mentors bias lessons toward their expertise',()=>{const j=createJourney(base);choose(j,'event','mentor');choose(j,'mentor','koushirou');assert(nextJourneyStep(j).options.some(o=>o.value==='weaponMastery_1'&&o.note.includes('Koushirou')));choose(j,'target','weaponMastery_1');choose(j,'trainingInstinct','Steady discipline');choose(j,'trainingResult','steady');assert.equal(j.story.mentored,1);assert.match(j.log[0].effects.join(' '),/Koushirou/);});
test('mapped travel records real location ids and dreams still require experience',()=>{const j=createJourney(origin({dream:'Find the One Piece'}));assert.equal(j.story.location,'Foosha Village');choose(j,'event','travel');assert(nextJourneyStep(j).options.some(o=>o.value==='island_dawn_island'));choose(j,'destination','island_dawn_island');assert.equal(nextJourneyStep(j).key,'travelResult');choose(j,'travelResult','safe');assert.equal(j.story.location,'Dawn Island');assert.equal(j.story.locationId,'island_dawn_island');assert(j.story.visitedIds.includes('island_dawn_island'));choose(j,'event','dream');choose(j,'dreamResult','milestone');assert.equal(j.story.dreamProgress,1);choose(j,'event','dream');assert(!nextJourneyStep(j).options.some(o=>o.value==='milestone'));assert.match(nextJourneyStep(j).note,/experience/);choose(j,'dreamResult','clue');assert.equal(j.story.dreamClues,1);});
test('mismatched dreams can change path through fate',()=>{const j=createJourney(origin({dream:'Become a Marine admiral'}));choose(j,'event','dream');choose(j,'dreamResult','commission');assert.equal(j.character.faction,'Marine');assert.equal(j.bounty,0);});
test('previous saves preserve pending generic encounters and then adopt story rules',()=>{const h=base,legacy=old.createJourney(h);old.applyJourneyRoll(legacy,'pirates');old.applyJourneyRoll(legacy,'seasoned');const loaded=loadDocument(old.saveDocument(h,legacy)).journey;assert(loaded.legacyPending);choose(loaded,'instinct','Urge to flee');choose(loaded,'resolution','escape');assert(!loaded.legacyPending);assert.equal(loaded.elapsedMonths,4);assert.equal(loaded.legacyCutover,4);choose(loaded,'event','marines');assert(nextJourneyStep(loaded).options.some(o=>o.value==='smoker'));assert.deepEqual(loadDocument(saveDocument(h,loaded)).journey,loaded);});
test('every new story stage round-trips, including bonds, death, and dream clues',()=>{const j=createJourney(base);for(const [key,value] of [['event','pirates'],['opponent','buggy'],['tone','hostile'],['instinct','Urge to flee'],['resolution','lethal'],['event','reflection'],['lifeResult','lead']]){choose(j,key,value);assert.deepEqual(loadDocument(saveDocument(base,j)).journey,j);}});
test('500 lifetimes keep every wheel resolvable and preserve complete new saves',()=>{for(let seed=1;seed<=500;seed++){const h=seed%5===0?origin({era:'Roger’s final voyage',race:'Giant',age:'220'}):base,j=createJourney(h),r=rng(seed);let spins=0;while(j.alive){const s=nextJourneyStep(j);assert(s?.options.length,`${s?.key} ${j.pending?.event}`);assert(s.options.every(o=>o.weight>0&&Number.isFinite(o.weight)));rollJourney(j,r);assert(++spins<10000);}assert(j.cause);assert(j.log.at(-1).alive===false);if(seed%50===0)assert.deepEqual(loadDocument(saveDocument(h,j)).journey,j);}});
test('migrating a fruit user mid-chapter preserves the same learning arc across reloads',()=>{const h=origin({devilFruit:'Yes',fruitMastery:'Just eaten'}),j=old.createJourney(h);old.applyJourneyRoll(j,'quiet');const migrated=loadDocument(old.saveDocument(h,j)).journey;choose(migrated,'quietResult','rest');assert.deepEqual(loadDocument(saveDocument(h,migrated)).journey,migrated);});
test('final swordsmanship claim requires actually defeating Mihawk',()=>{const j=createJourney(origin({dream:'Become the greatest swordsman'}));j.story.dreamProgress=3;j.elapsedMonths=120;j.story.visited=['Foosha Village','Water 7','Wano Country'];for(const k of Object.keys(j.skills))j.skills[k]=260;assert(dreamReadiness(j).needs.some(s=>s.includes('Mihawk')));j.story.relationships.mihawk={score:-2,meetings:1,last:1,victories:1};assert(dreamReadiness(j).ready);});
