import test from 'node:test';
import assert from 'node:assert/strict';
import {nextStep,roll,characterDocument} from '../src/engine.js';
import {createJourney,nextJourneyStep,applyJourneyRoll,rollJourney,combatOdds,boostOutcome,combatPower,saveDocument,loadDocument,naturalDeathChance,liveCharacter,levelOf} from '../src/journey-v1.js';
import {EVENTS} from '../src/journey-data-v1.js';
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
function origin(overrides={}){const h=[],r=rng(451);while(nextStep(h)){const s=nextStep(h);let item=roll(h,r);if(overrides[s.id]!==undefined){assert(s.options.some(o=>o.value===overrides[s.id]),s.id);item.value=overrides[s.id];}h.push(item);}return h;}
const base=origin({race:'Human',age:'24',faction:'Pirate',haki:'No',devilFruit:'No',fightingStyle:'Three-sword style',crewMode:'Form your own group',crewSize:'2',member_1_origin:'Original character',member_2_origin:'Original character'});
function choose(j,key,value){assert.equal(nextJourneyStep(j)?.key,key);applyJourneyRoll(j,value);}
function safeResolve(j){let guard=0;while(j.pending){const s=nextJourneyStep(j);const candidate=s.options.find(o=>['Live to see another chapter','Steady resolve','steady','rest','victory','safe','recover','stalled','held'].includes(o.value))||s.options.find(o=>!['death','Death from old age'].includes(o.value))||s.options[0];applyJourneyRoll(j,candidate.value);assert(++guard<12);}}
function battle(j,outcome='victory',instinct='Steady resolve'){choose(j,'event','pirates');choose(j,'opponent','seasoned');choose(j,'instinct',instinct);choose(j,'resolution',outcome);}
test('urge adds exactly 7 percentage points and renormalizes remaining outcomes',()=>{const base=[{value:'escape',weight:33},{value:'win',weight:33},{value:'lose',weight:34}];const after=boostOutcome(base,'escape',7);assert.equal(after[0].weight,40);assert(Math.abs(after.reduce((s,o)=>s+o.weight,0)-100)<1e-10);assert(Math.abs(after[1].weight/after[2].weight-33/34)<1e-10);});
test('one combat resolution, automatic urge, four months once',()=>{const j=createJourney(base),start=j.ageMonths;choose(j,'event','pirates');assert.equal(j.ageMonths,start);choose(j,'opponent','seasoned');choose(j,'instinct','Urge to flee');const s=nextJourneyStep(j);assert.equal(s.key,'resolution');assert.equal(s.modifier.after-s.modifier.before,7);assert.equal(j.ageMonths,start);choose(j,'resolution','escape');assert.equal(j.ageMonths,start+4);assert.equal(j.chapter,1);assert.equal(j.pending,null);assert.equal(nextJourneyStep(j).key,'event');assert.equal(j.log[0].rolls.length,4);});
test('skills, injuries, allies and enemy power alter combat odds',()=>{const j=createJourney(base),weak=combatOdds(j,'elite').options.find(o=>o.value==='victory').weight;for(const k of Object.keys(j.skills))j.skills[k]=260;const strong=combatOdds(j,'elite').options.find(o=>o.value==='victory').weight;assert(strong>weak);const power=combatPower(j);j.injury=5;assert(combatPower(j)<power);const noInjury=combatOdds(j,'rookie').options.find(o=>o.value==='victory').weight;assert(noInjury>combatOdds(j,'legend').options.find(o=>o.value==='victory').weight);});
test('combat outcomes apply distinct consequences and death locks the run',()=>{for(const result of ['victory','lethal','escape','wounded','spared','captured','death']){const j=createJourney(base);battle(j,result);assert.equal(j.chapter,1);if(result==='lethal')assert.equal(j.kills,1);if(result==='wounded')assert.equal(j.injury,2);if(result==='captured'){assert(j.captured);assert.deepEqual(nextJourneyStep(j).options.map(o=>o.value),['prison','prisonBreak']);}if(result==='death'){assert.equal(nextJourneyStep(j),null);assert.throws(()=>applyJourneyRoll(j,'victory'));assert.equal(j.alive,false);}}});
test('captivity resolves through one escape wheel and restores event pool',()=>{const j=createJourney(base);battle(j,'captured');choose(j,'event','prisonBreak');choose(j,'escapeResult','free');assert.equal(j.captured,false);assert(nextJourneyStep(j).options.some(o=>o.value==='training'));assert.equal(j.elapsedMonths,8);});
test('practice accumulates, instinct modifier shown, time skip replaces four months',()=>{const j=createJourney(base),before=j.skills.strength;choose(j,'event','timeskip');choose(j,'duration','24');choose(j,'target','strength');choose(j,'trainingInstinct','Sudden inspiration');assert.equal(nextJourneyStep(j).modifier.after,22);choose(j,'trainingResult','breakthrough');assert.equal(j.elapsedMonths,24);assert.equal(j.skills.strength,Math.min(260,before+90));assert.equal(j.log[0].months,24);});
test('existing fruit user cannot eat another, stored fruits can be used in a later chapter',()=>{const j=createJourney(base);choose(j,'event','fruit');choose(j,'fruitType','Logia');const fruit=nextJourneyStep(j).options[0].value;choose(j,'fruitName',fruit);choose(j,'fruitOutcome','store');assert.equal(j.inventory[0].name,fruit);choose(j,'event','provisions');choose(j,'storedFruit',fruit);choose(j,'fruitOutcome','eat');assert.equal(j.character.fruit,fruit);assert(!j.inventory.some(i=>i.name===fruit));choose(j,'event','fruit');choose(j,'fruitType','Logia');assert(!nextJourneyStep(j).options.some(o=>o.value===fruit));choose(j,'fruitName',nextJourneyStep(j).options[0].value);assert(!nextJourneyStep(j).options.some(o=>o.value==='eat'));});
test('new Haki appears on the live character and can be trained',()=>{const j=createJourney(base);choose(j,'event','haki');choose(j,'awakening','yes');choose(j,'hakiType','haki_armament');assert.equal(liveCharacter(j).haki,'Yes');assert.equal(liveCharacter(j).haki_armament,'Newly awakened');choose(j,'event','training');assert(nextJourneyStep(j).options.some(o=>o.value==='haki_armament'));});
test('world consequences persist and affect later encounters',()=>{const j=createJourney(base);const old=combatOdds(j,'seasoned').enemy;choose(j,'event','world');choose(j,'worldResult','War engulfs a kingdom');assert.equal(j.danger,2);assert(combatOdds(j,'seasoned').enemy>old);});
test('giants outlive human baseline, skips accumulate aging and never pass hard cap',()=>{assert(naturalDeathChance('Human',80*12,4)>naturalDeathChance('Giant',80*12,4));assert(naturalDeathChance('Human',80*12,120)>naturalDeathChance('Human',80*12,4));const j=createJourney(base);j.ageMonths=119*12;choose(j,'event','timeskip');choose(j,'duration','120');choose(j,'target','strength');choose(j,'trainingInstinct','Steady discipline');choose(j,'trainingResult','steady');assert.equal(j.ageMonths,120*12);assert.equal(j.pending.months,12);assert.equal(nextJourneyStep(j).key,'aging');assert.deepEqual(nextJourneyStep(j).options.map(o=>o.value),['Death from old age']);choose(j,'aging','Death from old age');assert.equal(j.cause,'Old age');assert.equal(j.chapter,1);assert.match(j.log[0].result,/old age/);});
test('old-age check does not double-advance a regular chapter',()=>{const j=createJourney(base);j.ageMonths=75*12;choose(j,'event','quiet');choose(j,'quietResult','rest');assert.equal(j.ageMonths,75*12+4);choose(j,'aging','Live to see another chapter');assert.equal(j.ageMonths,75*12+4);assert.equal(j.elapsedMonths,4);});
test('legacy origin saves migrate; every pending stage survives a replay roundtrip',()=>{assert.equal(loadDocument(characterDocument(base)).journey,null);const j=createJourney(base);for(const [key,value] of [['event','pirates'],['opponent','seasoned'],['instinct','Urge to flee'],['resolution','captured'],['event','prisonBreak'],['escapeResult','death']]){choose(j,key,value);const reloaded=loadDocument(JSON.parse(JSON.stringify(saveDocument(base,j))));assert.deepEqual(reloaded.journey,j);}assert.equal(loadDocument(saveDocument(base,j)).journey.alive,false);});
test('tampered, out-of-order and post-death saves are rejected',()=>{const j=createJourney(base);battle(j,'death');const saved=saveDocument(base,j);const forged=structuredClone(saved);forged.journey.rolls.push({id:'2:event',value:'quiet'});assert.throws(()=>loadDocument(forged));const other=structuredClone(saved);other.journey.rolls[0].value='<script>';assert.throws(()=>loadDocument(other));});
test('every normal event has a nonempty resolvable path',()=>{for(const [id] of EVENTS){const j=createJourney(base);j.bounty=5000;if(id==='provisions')j.inventory.push({name:'Smoke-Smoke / Moku Moku',type:'fruit',count:1});choose(j,'event',id);safeResolve(j);assert.equal(j.chapter,1,id);assert(j.ageMonths>j.startAgeMonths);}});
test('1,000 complete lifetimes: bounded odds, monotonic clocks, valid saves and terminal death',()=>{for(let seed=1;seed<=1000;seed++){const r=rng(seed),h=seed%10===0?origin({race:'Giant',age:'220'}):base,j=createJourney(h);let spins=0,lastAge=j.ageMonths;while(j.alive){const s=nextJourneyStep(j);assert(s&&s.options.length);assert(s.options.every(o=>Number.isFinite(o.weight)&&o.weight>0));rollJourney(j,r);assert(j.ageMonths>=lastAge);lastAge=j.ageMonths;assert(j.injury>=0&&j.injury<=5);assert(j.berries>=0);assert(++spins<10000);}assert.equal(nextJourneyStep(j),null);assert(j.cause);assert(j.log.at(-1).alive===false);if(seed%50===0)assert.deepEqual(loadDocument(saveDocument(h,j)).journey,j);}});
test('Conqueror rarity is not inflated when the common Haki types are already held',()=>{const j=createJourney(base);j.skills.haki_observation=0;j.skills.haki_armament=0;choose(j,'event','haki');const yes=nextJourneyStep(j).options.find(o=>o.value==='yes');assert.equal(yes.weight,.016);choose(j,'awakening','yes');assert.deepEqual(nextJourneyStep(j).options.map(o=>o.value),['haki_conqueror']);});
test('gifted fruits improve ally support and cannot be found a second time while held',()=>{const j=createJourney(base),before=combatPower(j);choose(j,'event','fruit');choose(j,'fruitType','Logia');const fruit=nextJourneyStep(j).options[0].value;choose(j,'fruitName',fruit);choose(j,'fruitOutcome','gift');assert.equal(j.crew[0].fruit,fruit);assert(combatPower(j)>before);choose(j,'event','fruit');choose(j,'fruitType','Logia');assert(!nextJourneyStep(j).options.some(o=>o.value===fruit));});
