// All weights are authored game balance, never canonical census data.
export const options = rows => rows.map(row => typeof row === 'string' ? {value:row,label:row,weight:1} : {value:row[0],label:row[0],weight:row[1],note:row[2] || ''});
export const races = options([
 ['Human',8800,'The most common people across the seas.'],['Fish-man',350,'Aquatic breathing and powerful physique; a fruit still removes swimming ability.'],['Merfolk',250,'Aquatic heritage and a tail; fighting styles are adapted to your anatomy.'],['Mink',180,'Electro potential. Sulong requires a full moon and training.'],['Sky Islander',180,'Sky-island heritage; wings do not automatically grant flight.'],['Longarm',70,'Two elbow joints in each arm.'],['Longleg',65,'Long legs and reach.'],['Giant',40,'Enormous size, long lifespan and exceptional baseline strength.'],['Dwarf',35,'Tiny stature, surprising strength and agility.'],['Snakeneck',20,'An elongated neck.'],['Three-eye',8,'A rare third eye; special perception is not automatically awakened.'],['Lunarian',1,'Flame, wing and durability traits. Their use takes practice.'],['Buccaneer',1,'Rare giant-related heritage and a powerful build.']
]);
export const families = options([
 ['Monkey',12,'Family connection, not inherited Haki or guaranteed strength.'],['Portgas',7,'A hidden family history; no automatic combat gift.'],['Gol',2,'A dangerous legacy, carrying D.'],['Trafalgar',8,'A concealed D. lineage; medicine is a roleplay hook.'],['Jaguar',5,'A giant family carrying D.'],['Nefertari',10,'Royal ancestry and a concealed D. legacy.'],['Vinsmoke',12,'Royal ties and scientific resources; genetic enhancements are NOT assumed.'],['Shimotsuki',16,'Wano swordsmith and samurai connections; training must be earned.'],['Kozuki',8,'Wano nobility; stone-carving knowledge requires teaching.'],['Donquixote',10,'World Noble ancestry; no automatic authority.'],['Charlotte',10,'A sprawling family; parentage does not guarantee powers.']
]);
export const dFamilies = ['Monkey','Portgas','Gol','Trafalgar','Jaguar','Nefertari'];
export const mastery = options([['Untrained',35],['Novice',35],['Practiced',20],['Expert',8],['Master',1.8],['Legendary',0.2]]);
export const hakiMastery = options([['Newly awakened',57],['Basic control',30],['Skilled',11],['Advanced technique',1.9],['World-class',0.1]]);
export const fruitMastery = options([['Just eaten',40],['Basic control',35],['Creative techniques',18],['Expert control',6],['Awakened',1]]);
export const stats = options([['Ordinary',44],['Trained',32],['Exceptional',17],['Elite',6],['Monstrous',0.9],['Legendary',0.1]]);
export const fruits = {
 Paramecia: options([['Chop-Chop / Bara Bara',12],['Slip-Slip / Sube Sube',10],['Kilo-Kilo / Kilo Kilo',10],['Bomb-Bomb / Bomu Bomu',8],['Wax-Wax / Doru Doru',10],['Clone-Clone / Mane Mane',8],['Flower-Flower / Hana Hana',6],['Dice-Dice / Supa Supa',7],['Spike-Spike / Toge Toge',8],['Cage-Cage / Ori Ori',8],['Spring-Spring / Bane Bane',10],['Slow-Slow / Noro Noro',6],['Door-Door / Doa Doa',6],['Hollow-Hollow / Horo Horo',5],['Revive-Revive / Yomi Yomi',3,'Revival is conditional on death; Brook’s learned techniques are not automatic.'],['Shadow-Shadow / Kage Kage',4],['Clear-Clear / Suke Suke',5],['Paw-Paw / Nikyu Nikyu',1],['Op-Op / Ope Ope',1],['String-String / Ito Ito',3],['Venom-Venom / Doku Doku',3],['Magnet-Magnet / Jiki Jiki',4],['Quake-Quake / Gura Gura',0.5],['Soul-Soul / Soru Soru',0.5],['Mochi-Mochi / Mochi Mochi',2,'Special Paramecia, not a Logia.']]),
 'Standard Zoan': options(['Ox-Ox, Bison model','Ox-Ox, Giraffe model','Cat-Cat, Leopard model','Dog-Dog, Dachshund model','Dog-Dog, Jackal model','Dog-Dog, Wolf model','Bird-Bird, Falcon model','Bird-Bird, Albatross model','Horse-Horse','Mole-Mole','Human-Human','Snake-Snake, King Cobra model','Snake-Snake, Anaconda model','Turtle-Turtle','Bug-Bug, Rhinoceros Beetle model','Bug-Bug, Hornet model']),
 'Ancient Zoan': options(['Dragon-Dragon, Allosaurus model','Dragon-Dragon, Spinosaurus model','Dragon-Dragon, Pteranodon model','Dragon-Dragon, Brachiosaurus model','Dragon-Dragon, Pachycephalosaurus model','Dragon-Dragon, Triceratops model','Elephant-Elephant, Mammoth model','Cat-Cat, Saber Tiger model','Spider-Spider, Rosamygale Grauvogeli model']),
 'Mythical Zoan': options([['Bird-Bird, Phoenix model',8],['Human-Human, Buddha model',4],['Fish-Fish, Azure Dragon model',3],['Dog-Dog, Nine-Tailed Fox model',6],['Dog-Dog, Okuchi-no-Makami model',4],['Snake-Snake, Yamata-no-Orochi model',6],['Human-Human, Onyudo model',8],['Human-Human, Nika model',1,'Rubber-like powers at first. Awakening is not automatic.']]),
 Logia: options([['Smoke-Smoke / Moku Moku',20],['Sand-Sand / Suna Suna',15],['Flame-Flame / Mera Mera',12],['Rumble-Rumble / Goro Goro',5],['Ice-Ice / Hie Hie',5],['Dark-Dark / Yami Yami',2,'Does not grant the usual elemental intangibility.'],['Glint-Glint / Pika Pika',3],['Magma-Magma / Magu Magu',3],['Swamp-Swamp / Numa Numa',20],['Gas-Gas / Gasu Gasu',10],['Snow-Snow / Yuki Yuki',15],['Woods-Woods / Mori Mori',4]])
};
export const swords = options([['Forged katana',60],['Naval saber',30],['Heavy cutlass',25],['Shigure',6],['Yubashiri',3],['Sandai Kitetsu',3],['Kashu',3],['Wado Ichimonji',0.6],['Shusui',0.6],['Enma',0.4],['Ame no Habakiri',0.4],['Nidai Kitetsu',0.4],['Yoru',0.1],['Ace',0.1],['Shodai Kitetsu',0.1]]);
// Era indexes: Roger's final voyage; early Great Pirate Era; Summit War opening; New World opening.
export const crewCatalog = [
 ['Roger Pirates',[0],'Pirate'],['Whitebeard Pirates',[0,1,2],'Pirate'],['Red Hair Pirates',[1,2,3],'Pirate'],['Straw Hat Pirates',[2,3],'Pirate'],['Heart Pirates',[2,3],'Pirate'],['Kid Pirates',[2,3],'Pirate'],['Sun Pirates',[1,2,3],'Pirate'],['Kuja Pirates',[0,1,2,3],'Pirate'],['Beast Pirates',[1,2,3],'Pirate'],['Big Mom Pirates',[0,1,2,3],'Pirate'],['Blackbeard Pirates',[2,3],'Pirate'],['East Blue Marine branch',[0,1,2,3],'Marine'],['Marine Headquarters unit',[0,1,2,3],'Marine'],['G-5 unit',[3],'Marine'],['Revolutionary Army cell',[1,2,3],'Revolutionary'],['Freedom Fighters',[0],'Revolutionary'],['Cipher Pol field unit',[0,1,2,3],'Cipher Pol'],['Bounty hunter guild',[0,1,2,3],'Bounty hunter'],['Merchant convoy',[0,1,2,3],'Merchant'],['Independent expedition',[0,1,2,3],'Explorer'],['Island community',[0,1,2,3],'Civilian']
].map(([name,eras,faction])=>({name,eras,faction}));
export const characters = [
 ['Silvers Rayleigh',[0,1,2,3],'Pirate',1],['Scopper Gaban',[0,1,2,3],'Pirate',1],['Crocus',[0,1,2,3],'Pirate',3],['Kozuki Oden',[0],'Pirate',1],['Shanks',[1,2,3],'Pirate',1],['Benn Beckman',[1,2,3],'Pirate',2],['Yasopp',[1,2,3],'Pirate',3],['Marco',[0,1,2,3],'Pirate',2],['Jozu',[0,1,2,3],'Pirate',3],['Vista',[0,1,2,3],'Pirate',4],['Ace',[2],'Pirate',1],['Luffy',[2,3],'Pirate',1],['Zoro',[2,3],'Pirate',2],['Nami',[2,3],'Pirate',5],['Usopp',[2,3],'Pirate',8],['Sanji',[2,3],'Pirate',3],['Chopper',[2,3],'Pirate',6],['Robin',[2,3],'Pirate',4],['Franky',[2,3],'Pirate',5],['Brook',[2,3],'Pirate',4],['Jinbe',[1,2,3],'Pirate',3],['Law',[2,3],'Pirate',1],['Bepo',[2,3],'Pirate',8],['Penguin',[2,3],'Pirate',10],['Shachi',[2,3],'Pirate',10],['Killer',[2,3],'Pirate',3],['Hatchan',[1,2,3],'Pirate',10],['Garp',[0,1,2,3],'Marine',1],['Sengoku',[0,1,2,3],'Marine',1],['Tsuru',[0,1,2,3],'Marine',2],['Smoker',[2,3],'Marine',4],['Tashigi',[2,3],'Marine',10],['Koby',[2,3],'Marine',8],['Helmeppo',[2,3],'Marine',12],['Hina',[2,3],'Marine',6],['Dragon',[1,2,3],'Revolutionary',1],['Ivankov',[1,2,3],'Revolutionary',3],['Sabo',[3],'Revolutionary',2],['Koala',[3],'Revolutionary',10],['Belo Betty',[3],'Revolutionary',5],['Rob Lucci',[2,3],'Cipher Pol',2],['Kaku',[2,3],'Cipher Pol',5],['Kalifa',[2,3],'Cipher Pol',8],['Jabra',[2,3],'Cipher Pol',6],['Johnny',[2,3],'Bounty hunter',12],['Yosaku',[2,3],'Bounty hunter',12],['Daz Bonez',[2,3],'Bounty hunter',3],['Zeff',[1,2,3],'Civilian',3],['Iceburg',[2,3],'Civilian',5],['Paulie',[2,3],'Civilian',8],['Kaya',[2,3],'Civilian',8]
];
export const firstNames = ['Ren','Kaia','Rook','Mira','Finn','Sora','Nero','Iris','Taro','Vega','Mako','Luna','Flint','Coral','Jett','Aster','Rhea','Kiro','Dax','Nori'];
export const surnames = ['Storm','Vale','Drift','Reef','Voss','Ember','Tide','Flint','Marrow','Sable','Cross','Kestrel'];
export const dreams = options(['Find the One Piece','Chart every sea','Become the greatest swordsman','Discover the All Blue','Cure an incurable disease','Free an oppressed homeland','Uncover the lost history','Build a ship that circles the world','Protect a found family','End slavery','Become a Marine admiral','Find a lost relative','Create a sanctuary for every race','Become the richest merchant','Reach the moon','Write the true history of this era']);
