import {SAGAS,SAGA_BY_ID,sagaStatus,sagaScene,sagasEnabled,EFFECTS} from './sagas.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const outcomeText=(s,e)=>e.next?`Next: ${s.nodes[e.next].title}`:'Ending';
export function renderSagaJournal(j){
 if(!sagasEnabled(j))return '';
 const records=Object.entries(j.story.sagas||{}),active=records.filter(([,s])=>!s.ending),done=records.filter(([,s])=>s.ending);
 const available=SAGAS.filter(s=>sagaStatus(j,s).available);
 return `<section class="saga-journal" aria-label="Saga journal"><div class="compass-heading"><span class="eyebrow">THE THREADS YOU LEAVE BEHIND</span><span class="life-stage">${done.length} / ${SAGAS.length} concluded</span></div><h3>Promises have consequences.</h3><p>${active.length} unfinished · ${available.length} available here · Government heat ${j.story.sagaHeat||0}/10</p>${active.length?`<div class="saga-active-list">${active.map(([id,state])=>{const s=SAGA_BY_ID[id],status=sagaStatus(j,s);return `<article class="saga-active"><b>${esc(s.title)}</b><span>${esc(sagaScene(j,id).title)}</span><small>${esc(status.reason)} · Evidence ${state.evidence} · Trust ${state.trust}</small></article>`;}).join('')}</div>`:'<p class="empty-state">The horizon wheel can open a new saga. Each scene lasts four months; ordinary life continues between scenes.</p>'}${done.length?`<details><summary>Read your ${done.length} saga endings</summary>${done.map(([id,s])=>`<p><b>${esc(SAGA_BY_ID[id].title)}</b><br>${esc(s.ending)} · Chapter ${s.completedChapter}</p>`).join('')}</details>`:''}<details class="saga-atlas"><summary>Explore all ${SAGAS.length} sagas & their wheel branches</summary><p>Canon anchors establish the setting. Every mission, choice of response, outcome, and probability is authored fan fiction. The wheel chooses your response; this atlas is read-only.</p>${SAGAS.map(s=>{const status=sagaStatus(j,s),state=j.story.sagas?.[s.id];return `<details class="saga-map"><summary><span>${esc(s.title)}</span><small>${esc(status.reason)}</small></summary><p class="saga-anchor"><b>Canon anchor</b> · ${esc(s.anchor)} ${s.source?`<a href="${esc(s.source)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`:'Original side story.'}</p><p><b>Where:</b> ${esc(s.places.join(' / ')||'Any inhabited route')} · <b>Your record:</b> ${state?`${state.history.length} scenes resolved`:'Unwritten'}</p><ol class="saga-tree">${Object.entries(s.nodes).map(([id,n])=>`<li class="${state?.node===id?'current-node':''}"><h4>${esc(n.title)}${state?.node===id?' · NEXT THREAD':''}</h4><p>${esc(n.text)}</p><ul>${n.edges.map(e=>`<li><b>${esc(e.label)}</b><span>${esc(e.detail)}</span><small>→ ${esc(outcomeText(s,e))} · ${esc(EFFECTS[e.effect].label)}</small></li>`).join('')}</ul></li>`).join('')}</ol></details>`;}).join('')}</details></section>`;
}
