// Canon names and affiliations; encounter plots, ratings, odds, and reactions are authored fiction.
// Cast eligibility is a starting-era snapshot, not a prediction of later canon continuity.
export const REGIONS=['Blue Seas','Paradise','New World'];
export const PLACES=[
 ['Foosha Village',0,'A quiet harbor where a small boat can still carry a very large dream.'],
 ['Orange Town',0,'A rebuilt port with traveling performers and watchful merchants.'],
 ['Loguetown',0,'The streets of the beginning and the end attract Marines and ambitious rookies.'],
 ['Baratie',0,'A sea restaurant where hungry travelers trade stories over a meal.'],
 ['Cocoyasi Village',0,'Tangerine groves and a community that values freedom.'],
 ['Reverse Mountain',1,'The currents gather at the entrance to the Grand Line.'],
 ['Drum Island',1,'Snow-covered mountains shelter doctors and difficult journeys.'],
 ['Alabasta',1,'A desert kingdom where water, trust and information are precious.'],
 ['Water 7',1,'Shipwrights work beneath the sound of hammers and approaching tides.'],
 ['Sabaody Archipelago',1,'Coated ships wait at the threshold of a much more dangerous sea.'],
 ['Kuraigana Island',1,'Ruins and harsh terrain make this an unforgiving training ground.'],
 ['Fish-Man Island',2,'An undersea crossroads where a safe arrival is never taken for granted.'],
 ['Dressrosa',2,'A crowded kingdom of trade, spectacle and tangled allegiances.'],
 ['Zou',2,'An ancient traveling home, reached through trust and careful navigation.'],
 ['Whole Cake Island',2,'A colorful archipelago where hospitality may carry a price.'],
 ['Wano Country',2,'A closed country of samurai, craftsmanship and unfinished promises.'],
 ['Elbaf',2,'The land of giants, long memories and imposing warriors.'],
];
const all=[0,1,2,3],modern=[2,3];
const character=(id,name,crew,kind,eras,regions,power,weight,temper,style,hook,mentor=[])=>({id,name,crew,kind,eras,regions,power,weight,temper,style,hook,mentor});
export const CANON=[
 character('mihawk','Dracule Mihawk','Independent swordsman','pirate',[2,3],[0,1,2],125,1,'proud','Yoru and supreme swordsmanship','A small boat carries a swordsman whose presence unsettles an entire harbor.', ['weapon','fightingMastery']),
 character('blackbeard','Marshall D. Teach','Blackbeard Pirates','pirate',[2,3],[1,2],126,1,'scheming','Darkness and opportunistic tactics','A boisterous crew argues about destiny while its captain studies everyone in the room.'),
 character('kaido','Kaido','Beast Pirates','pirate',[1,2,3],[2],145,1,'cruel','Azure Dragon Zoan and kanabo','The harbor empties as a ship bearing the Beast Pirates’ flag approaches.'),
 character('king','King','Beast Pirates','pirate',[1,2,3],[2],109,3,'dutiful','Pteranodon Zoan and swordsmanship','A dark figure surveys the coast above a disciplined pirate landing party.'),
 character('bigmom','Charlotte Linlin','Big Mom Pirates','pirate',all,[2],142,1,'cruel','Soul-Soul power and immense strength','A richly decorated ship delivers an invitation that sounds more like a demand.'),
 character('katakuri','Charlotte Katakuri','Big Mom Pirates','pirate',[1,2,3],[2],104,3,'protective','Mochi power and Observation Haki','A watchful commander seems to anticipate trouble before anyone else notices it.'),
 character('jinbe','Jinbe','Sun Pirates','pirate',[1,2,3],[1,2],94,4,'protective','Fish-man Karate and Haki','A veteran helmsman helps guide a damaged ship into calmer water.', ['fightingMastery','haki_armament']),
 character('akainu','Sakazuki','Marine Headquarters','marine',all,[1,2],132,1,'cruel','Magma Logia','A Marine force arrives with strict orders and little patience for explanations.'),
 character('kizaru','Borsalino','Marine Headquarters','marine',all,[1,2],128,1,'dutiful','Light Logia','A deceptively unhurried admiral steps into the middle of a rapidly escalating situation.'),
 character('fujitora','Issho','Marine Headquarters','marine',[3],[1,2],124,1,'protective','Gravity power and swordsmanship','An admiral stops to hear the civilians before listening to the officials.'),
 character('alvida','Alvida','Alvida Pirates','pirate',modern,[0],14,18,'cruel','Iron mace','A ship blocks the harbor while its captain demands tribute.'),
 character('buggy','Buggy','Buggy Pirates','pirate',modern,[0,1],23,18,'scheming','Chop-Chop tricks and knives','A flashy flag appears over a dockside argument about treasure.'),
 character('kuro','Kuro','Black Cat Pirates','pirate',modern,[0],24,13,'scheming','Clawed blades and speed','A quiet ship approaches without raising a friendly signal.'),
 character('krieg','Don Krieg','Krieg Pirates','pirate',modern,[0,1],27,12,'cruel','Hidden weapons and armor','An armored captain wants provisions, and does not intend to pay.'),
 character('arlong','Arlong','Arlong Pirates','pirate',modern,[0],34,10,'cruel','Fish-man strength and saw blade','A familiar shark-shaped flag turns the harbor silent.'),
 character('luffy','Monkey D. Luffy','Straw Hat Pirates','pirate',modern,[0,1,2],75,8,'warm','Rubber-bodied brawling','A cheerful captain smells food before he notices your flag.'),
 character('zoro','Roronoa Zoro','Straw Hat Pirates','pirate',modern,[0,1,2],69,9,'proud','Three-sword style','A swordsman asks for directions, then notices your stance.', ['fightingMastery','weapon']),
 character('nami','Nami','Straw Hat Pirates','pirate',modern,[0,1,2],30,12,'practical','Weather tactics','A navigator studies your chart and immediately spots a mistake.', ['battleIQ']),
 character('sanji','Sanji','Straw Hat Pirates','pirate',modern,[0,1,2],65,9,'warm','Powerful kicks','A cook sets down a plate and asks when you last ate properly.', ['fightingMastery']),
 character('usopp','Usopp','Straw Hat Pirates','pirate',modern,[0,1,2],29,12,'warm','Slingshot marksmanship','A sharpshooter tells a suspiciously spectacular story about this island.', ['weapon','battleIQ']),
 character('crocodile','Crocodile','Baroque Works','pirate',modern,[1],70,5,'scheming','Sand Logia and a hook','An invitation arrives with no signature, only a promise of opportunity.'),
 character('bellamy','Bellamy','Bellamy Pirates','pirate',modern,[1],36,12,'proud','Spring-powered attacks','Laughter from a tavern turns into a challenge when you mention your dream.'),
 character('foxy','Foxy','Foxy Pirates','pirate',modern,[1],30,12,'scheming','Slow-Slow tricks','A grinning captain proposes a competition with suspicious rules.'),
 character('law','Trafalgar Law','Heart Pirates','pirate',modern,[1,2],82,6,'practical','Op-Op surgery and swordsmanship','A yellow submarine surfaces near a ship that needs a doctor.'),
 character('kid','Eustass Kid','Kid Pirates','pirate',modern,[1,2],84,4,'cruel','Magnetic weapons','Scrap metal begins to rattle as a red-haired captain steps ashore.'),
 character('bege','Capone Bege','Fire Tank Pirates','pirate',modern,[1,2],64,7,'scheming','Fortress tactics','A sharply dressed envoy offers a deal on behalf of the captain.'),
 character('shanks','Shanks','Red Hair Pirates','pirate',[1,2,3],[0,1,2],120,1,'warm','Swordsmanship and overwhelming Haki','A relaxed crew is laughing in the harbor, but every other ship keeps its distance.', ['haki','battleIQ']),
 character('beckman','Benn Beckman','Red Hair Pirates','pirate',[1,2,3],[0,1,2],100,2,'practical','Rifle and tactical command','A quiet marksman watches every exit while his crew celebrates.', ['weapon','battleIQ']),
 character('whitebeard','Edward Newgate','Whitebeard Pirates','pirate',[0,1,2],[1,2],125,1,'protective','Quake power and bisento','A vast ship enters the bay, sheltering smaller vessels in its wake.'),
 character('marco','Marco','Whitebeard Pirates','pirate',all,[1,2],95,3,'protective','Phoenix Zoan','Blue flames above a damaged ship reveal an unexpected rescuer.'),
 character('ace','Portgas D. Ace','Whitebeard Pirates','pirate',[2],[1,2],83,4,'warm','Flame Logia','A traveler asks whether you have seen a certain pirate nearby.'),
 character('roger','Gol D. Roger','Roger Pirates','pirate',[0],[1,2],130,1,'warm','Swordsmanship and Haki','A legendary ship puts into port as if this were an ordinary afternoon.'),
 character('rayleigh','Silvers Rayleigh','Roger Pirates / retired','pirate',all,[1],115,2,'practical','Swordsmanship and Haki','A ship-coating craftsman sees straight through your attempt to hide your nerves.', ['haki','fightingMastery','battleIQ']),
 character('dorry','Dorry','Giant Warrior Pirates','pirate',all,[1,2],100,3,'proud','Giant swordsmanship','A thunderous laugh rolls across the trees before you see its owner.'),
 character('brogy','Brogy','Giant Warrior Pirates','pirate',all,[1,2],100,3,'proud','Giant axe fighting','A giant warrior offers a feast and speaks of a very long rivalry.'),
 character('hancock','Boa Hancock','Kuja Pirates','pirate',modern,[1,2],100,2,'proud','Love-Love power and Haki','A serpent-prowed ship arrives under a strict order to keep outsiders away.'),
 character('doflamingo','Donquixote Doflamingo','Donquixote Pirates','pirate',modern,[1,2],100,2,'cruel','String-String manipulation','A broker claims your dream could be financed, for the right favor.'),
 character('morgan','Axe-Hand Morgan','153rd Marine Branch','marine',modern,[0],20,15,'cruel','Axe arm','A Marine checkpoint is collecting more than routine harbor dues.'),
 character('smoker','Smoker','Smoker’s Marine unit','marine',modern,[0,1,2],72,11,'dutiful','Smoke Logia and seastone jitte','Smoke curls over the pier as a Marine studies your flag and your face.'),
 character('tashigi','Tashigi','Smoker’s Marine unit','marine',modern,[0,1,2],40,14,'dutiful','Swordsmanship','An officer checks the blade at your side before asking about your business.', ['weapon']),
 character('hina','Hina','Hina’s Marine unit','marine',modern,[1],63,7,'dutiful','Cage-Cage restraints','A disciplined patrol closes off the harbor for an inspection.'),
 character('garp','Monkey D. Garp','Garp’s Marine unit','marine',all,[0,1,2],125,1,'protective','Fists and powerful Haki','A dog-headed warship arrives; its commander seems more interested in lunch than ceremony.', ['fightingMastery','haki']),
 character('koby','Koby','Marines','marine',modern,[0,1,2],38,13,'protective','Marine hand-to-hand training','A young Marine is helping civilians before tending to official business.'),
 character('helmeppo','Helmeppo','Marines','marine',modern,[0,1],29,15,'dutiful','Paired blades','A Marine catches his breath after a difficult training session.'),
 character('momonga','Momonga','Marine Headquarters','marine',modern,[1,2],88,4,'dutiful','Swordsmanship and Haki','A vice-admiral’s ship anchors with precise, unsettling efficiency.'),
 character('sengoku','Sengoku','Marine Headquarters','marine',all,[1,2],123,1,'dutiful','Buddha Zoan and strategy','Orders from Headquarters bring a renowned commander into your waters.'),
 character('johnny','Johnny','Johnny & Yosaku','hunter',modern,[0],13,18,'warm','Bounty-hunter swordsmanship','A hungry bounty hunter tries to decide whether your poster is worth the trouble.'),
 character('yosaku','Yosaku','Johnny & Yosaku','hunter',modern,[0],13,18,'warm','Bounty-hunter swordsmanship','A bounty hunter approaches with a worn poster and an uncertain expression.'),
 character('daz','Daz Bonez','Baroque Works','hunter',modern,[1],57,5,'dutiful','Steel-bodied martial arts','An exceptionally calm hunter waits beside the only road out of town.'),
 character('crocus','Crocus','Twin Cape / former Roger Pirates','mentor',all,[1],46,10,'practical','Medicine and seamanship','A lighthouse keeper listens to your plans beside a restless sea.', ['battleIQ']),
 character('koushirou','Koushirou','Isshin Dojo','mentor',all,[0],60,10,'practical','Swordsmanship','The dojo master invites you to repeat one simple movement until you understand it.', ['weapon','fightingMastery']),
 character('zeff','Zeff','Baratie','mentor',[1,2,3],[0],57,10,'practical','Kicking style and cooking','The head chef offers work, a meal, and an uncompromising lesson.', ['fightingMastery','battleIQ']),
 character('kureha','Dr. Kureha','Drum Island','mentor',all,[1],42,10,'practical','Medicine and hard-earned experience','A doctor with no patience for excuses asks what you are trying to learn.', ['battleIQ']),
 character('hyogoro','Hyogoro','Wano samurai','mentor',all,[2],80,6,'protective','Armament Haki and swordsmanship','An old master demonstrates how little wasted motion a veteran needs.', ['haki_armament','weapon']),
 character('ivankov','Emporio Ivankov','Revolutionary Army','revolutionary',[1,2,3],[1,2],91,4,'protective','Hormone power and martial arts','A flamboyant revolutionary sees a chance to help someone reinvent their life.', ['fightingMastery','battleIQ']),
 character('sabo','Sabo','Revolutionary Army','revolutionary',[3],[1,2],103,3,'protective','Dragon-claw martial arts','A revolutionary officer asks who truly benefits from the island’s unrest.', ['haki_armament','fightingMastery']),
 character('koala','Koala','Revolutionary Army','revolutionary',[3],[1,2],48,8,'warm','Fish-man Karate','A revolutionary instructor is quietly training a group of volunteers.', ['fightingMastery']),
];
export const DREAMS={
 'Find the One Piece':{theme:'The last island',focus:['island','travel','dream','mentor'],skill:'battleIQ',steps:['Trace a credible lead to the Road Poneglyphs','Follow a lead to a first Road Poneglyph rubbing','Secure a route assembled from the remaining rubbings','Sail to Laugh Tale and discover the One Piece'],epic:true},
 'Chart every sea':{theme:'An atlas without blank spaces',focus:['travel','island','dream'],skill:'battleIQ',steps:['Complete a chart of your home waters','Map a dangerous Grand Line passage','Chart an unexplored New World route','Publish an atlas spanning every sea']},
 'Become the greatest swordsman':{theme:'A blade with a name',focus:['training','mentor','duel','dream'],skill:'weaponMastery_1',steps:['Earn recognition in a local sword contest','Defeat an established master','Build a reputation across the New World','Win the challenge that establishes your claim as greatest'],combat:true},
 'Discover the All Blue':{theme:'Where the four seas meet',focus:['travel','trade','island','dream'],skill:'battleIQ',steps:['Collect accounts from cooks and fishermen','Identify currents that connect distant seas','Follow a trail of fish from all four seas','Reach the All Blue and share its bounty'],epic:true},
 'Cure an incurable disease':{theme:'A cure worth chasing',focus:['mentor','island','rescue','dream'],skill:'battleIQ',steps:['Document the illness with a trusted doctor','Find a promising rare ingredient','Help develop and test a workable treatment','Deliver a cure to the people who need it']},
 'Free an oppressed homeland':{theme:'A home worth returning to',focus:['rescue','recruit','world','dream'],skill:'fightingMastery',steps:['Learn who holds power over your home','Build a network of allies','Break the regime’s strongest foothold','Return home and win its freedom'],combat:true},
 'Uncover the lost history':{theme:'The words they tried to erase',focus:['island','mentor','dream','travel'],skill:'battleIQ',steps:['Recover a suppressed historical record','Find someone who can interpret the evidence','Connect accounts from several ancient sites','Reveal a coherent account of the lost history'],epic:true},
 'Build a ship that circles the world':{theme:'A ship for the impossible voyage',focus:['trade','treasure','travel','dream'],skill:'battleIQ',steps:['Draw a design with a master shipwright','Secure rare timber and reliable equipment','Complete and test the vessel','Bring your ship home after a world-circling voyage']},
 'Protect a found family':{theme:'A place at your table',focus:['recruit','rescue','leadership','dream'],skill:'fightingMastery',steps:['Give a stranded traveler a safe place','Build trust within a circle of companions','Defend your people through a crisis','Establish a lasting safe home for your found family']},
 'End slavery':{theme:'No one left in chains',focus:['rescue','world','recruit','dream'],skill:'fightingMastery',steps:['Expose a local trafficking operation','Establish an escape route with allies','Dismantle a powerful trafficking network','Forge an alliance capable of enforcing abolition'],epic:true,combat:true},
 'Become a Marine admiral':{theme:'Justice with your own voice',focus:['marines','training','rescue','dream'],skill:'fightingMastery',steps:['Earn a commendation for protecting civilians','Prove you can command a difficult operation','Build the record of a senior Marine officer','Receive appointment to admiral'],combat:true},
 'Find a lost relative':{theme:'Someone is still out there',focus:['travel','trade','mentor','dream'],skill:'battleIQ',steps:['Find a witness who remembers your relative','Trace their passage across the Grand Line','Discover where their journey ended','Reunite and hear the story you have been missing']},
 'Create a sanctuary for every race':{theme:'A harbor for everyone',focus:['recruit','rescue','trade','dream'],skill:'battleIQ',steps:['Help people from different communities find safety','Secure land and local support','Build a settlement that can protect itself','Open a lasting sanctuary to every people']},
 'Become the richest merchant':{theme:'A fortune that sails',focus:['trade','treasure','travel','dream'],skill:'battleIQ',steps:['Build a reliable trade route','Establish a profitable trading company','Develop a network spanning the New World','Become the leading merchant of your alternate era']},
 'Reach the moon':{theme:'Beyond the last horizon',focus:['island','mentor','treasure','dream'],skill:'battleIQ',steps:['Recover notes about skyward travel','Find a builder willing to attempt the impossible','Construct and test an extraordinary vessel','Complete your first voyage to the moon'],epic:true},
 'Write the true history of this era':{theme:'A witness to the age',focus:['world','travel','mentor','dream'],skill:'battleIQ',steps:['Record the stories of your first islands','Collect testimony from rival sides','Preserve evidence others want destroyed','Publish a history that survives its powerful critics']},
};
